name: Paintball
version: 2.0
main: me.chocoaa.paintball.Paintball
author: chocoaa
description: A fully functional paintball plugin!

commands:
     paintball:
        usage: /<command> <args> [optional args]
        aliases: [pb]
        description: Paintball Command